# pyproject.toml
[tool.black]
line-length = 88
target-version = ['py39','py310','py311']
include = '*.py'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
